[package]
name = "valens-frontend"
version = "0.0.0"
authors = ["Tobias Reiher <valens@ardeidae.de>"]
edition = "2021"

[dependencies]
seed = "0.8"
serde = "1.0"
serde_json = "1.0"
wasm-bindgen = "=0.2.74"
